/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankingsystem;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/**
 *
 * @author mahdi
 */
public class ChangeUserDataPage extends javax.swing.JFrame {
    
    String currentUsername;
    /**
     * Creates new form ChangeUserDataPage
     */
    public ChangeUserDataPage(String currentUsername) {
        initComponents();
        this.currentUsername=currentUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldModifiedLastName = new javax.swing.JTextField();
        jTextFieldModifiedFirstName = new javax.swing.JTextField();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();
        jButtonBackFromChangeData = new javax.swing.JButton();
        EnterNewData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Change Client Data");

        jLabel3.setText("New Password");

        jLabel4.setText("Modified First Name");

        jLabel5.setText("Modified Last Name");

        jButtonBackFromChangeData.setText("Back");
        jButtonBackFromChangeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackFromChangeDataActionPerformed(evt);
            }
        });

        EnterNewData.setText("Enter");
        EnterNewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNewDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldModifiedLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(jTextFieldModifiedFirstName))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButtonBackFromChangeData)
                        .addGap(79, 79, 79)
                        .addComponent(EnterNewData)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModifiedFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldModifiedLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackFromChangeData)
                    .addComponent(EnterNewData))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNewDataActionPerformed
        // TODO add your handling code here:
        User CurrentUser;
        try
        {   
            // Reading the object from a file
            FileInputStream ifile = new FileInputStream(currentUsername+"data.ser");
            ObjectInputStream in = new ObjectInputStream(ifile);
              
            // Method for deserialization of object
            CurrentUser = (User)in.readObject();
              
            in.close();
            ifile.close();
              
            if (!"".equals(jPasswordFieldNewPassword.getText()))
                CurrentUser.password=jPasswordFieldNewPassword.getText();
            if (!"".equals(jTextFieldModifiedFirstName.getText()))
               CurrentUser.firstName=jTextFieldModifiedFirstName.getText();
            if (!"".equals(jTextFieldModifiedLastName.getText()))
               CurrentUser.lastName=jTextFieldModifiedLastName.getText();
            try
             {   
            //Saving of object in a file
            FileOutputStream ofile = new FileOutputStream(currentUsername+"data.ser");
            ObjectOutputStream out = new ObjectOutputStream(ofile);
              
            // Method for serialization of object
            out.writeObject(CurrentUser);
              
            out.close();
            ofile.close();
              
            System.out.println("Object has been serialized");          
            }
             catch(IOException ex){
            System.out.println("IOException is caught");
             }
        
        }
          
        catch(IOException ex)
        {
            System.out.println("IOException is caught");
        }
          
        catch(ClassNotFoundException ex)
        {
            System.out.println("ClassNotFoundException is caught");
        
    
       }      
        
        
        
        
    }//GEN-LAST:event_EnterNewDataActionPerformed

    private void jButtonBackFromChangeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackFromChangeDataActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonBackFromChangeDataActionPerformed

   
   //  * @param args the command line arguments
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterNewData;
    private javax.swing.JButton jButtonBackFromChangeData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JTextField jTextFieldModifiedFirstName;
    private javax.swing.JTextField jTextFieldModifiedLastName;
    // End of variables declaration//GEN-END:variables
}
