/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankingsystem;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author mahdi
 */
public class DepositMoney extends javax.swing.JFrame {

    /**
     * Creates new form DepositMoney
     */
    String currentUsername;
    public DepositMoney(String currentUsername) {
        initComponents();
        this.currentUsername=currentUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amountToDeposit = new javax.swing.JTextField();
        jButtonBackFromDepositPage = new javax.swing.JButton();
        jButtonEnterDepositInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Make a deposit");

        jLabel2.setText("Amount to deposit ");

        amountToDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountToDepositActionPerformed(evt);
            }
        });

        jButtonBackFromDepositPage.setText("Back");
        jButtonBackFromDepositPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackFromDepositPageActionPerformed(evt);
            }
        });

        jButtonEnterDepositInfo.setText("Enter");
        jButtonEnterDepositInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterDepositInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(amountToDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButtonBackFromDepositPage)
                        .addGap(67, 67, 67)
                        .addComponent(jButtonEnterDepositInfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(amountToDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackFromDepositPage)
                    .addComponent(jButtonEnterDepositInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountToDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountToDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountToDepositActionPerformed

    private void jButtonEnterDepositInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterDepositInfoActionPerformed
        try {
            // TODO add your handling code here:
            if ("".equals(amountToDeposit.getText())){
            InputIssue InputIssue =new InputIssue();
             InputIssue.setVisible(true);
            }
            
            else {
             Writer fileWriter = new FileWriter(currentUsername+"history.txt", true);
            PrintWriter printWriter = new PrintWriter(fileWriter);
            printWriter.println(amountToDeposit.getText()+"   "+"Deposit"+"   "+java.time.LocalDate.now().toString());
            printWriter.close();
            }
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_jButtonEnterDepositInfoActionPerformed

    private void jButtonBackFromDepositPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackFromDepositPageActionPerformed
        // TODO add your handling code here:4dispose();
        dispose();
    }//GEN-LAST:event_jButtonBackFromDepositPageActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountToDeposit;
    private javax.swing.JButton jButtonBackFromDepositPage;
    private javax.swing.JButton jButtonEnterDepositInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
