/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankingsystem;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author mahdi
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    String username;
    public WelcomePage(String currentUsername) {
        initComponents();
        username=currentUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jDepositButton = new javax.swing.JButton();
        jSpendMoneyButton = new javax.swing.JButton();
        jHistoryButton = new javax.swing.JButton();
        changeCurrency = new javax.swing.JButton();
        jLogOutButton = new javax.swing.JButton();
        Balance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDepositButton.setText("Make a deposit.");
        jDepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepositButtonActionPerformed(evt);
            }
        });

        jSpendMoneyButton.setText("Spend money.");
        jSpendMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpendMoneyButtonActionPerformed(evt);
            }
        });

        jHistoryButton.setText("Check you history of transactions.");
        jHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHistoryButtonActionPerformed(evt);
            }
        });

        changeCurrency.setText("Change your default currency.");
        changeCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCurrencyActionPerformed(evt);
            }
        });

        jLogOutButton.setText("Log Out");
        jLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonActionPerformed(evt);
            }
        });

        Balance.setText("Get Your Balance");
        Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLogOutButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpendMoneyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDepositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeCurrency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Balance)
                .addGap(18, 18, 18)
                .addComponent(jDepositButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSpendMoneyButton)
                .addGap(18, 18, 18)
                .addComponent(jHistoryButton)
                .addGap(18, 18, 18)
                .addComponent(changeCurrency)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLogOutButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepositButtonActionPerformed
        // TODO add your handling code here:
        File tmpFile = new File(username+"data.ser");
        boolean Valid = tmpFile.exists();
        if (Valid ){
         DepositMoney DepositMoney = new DepositMoney(username);
         DepositMoney.setVisible(true);}
          else{
          InputIssue InputIssue =new InputIssue();
          InputIssue.setVisible(true);
        }
    }//GEN-LAST:event_jDepositButtonActionPerformed

    private void changeCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCurrencyActionPerformed
        // TODO add your handling code here:
         File tmpFile = new File(username+"data.ser");
        boolean Valid = tmpFile.exists();
        if (Valid ){
        ChangingCurrency ChangingCurrency = new ChangingCurrency(username);
        ChangingCurrency.setVisible(true);}
          else{
          InputIssue InputIssue =new InputIssue();
          InputIssue.setVisible(true);
        }
    }//GEN-LAST:event_changeCurrencyActionPerformed

    private void jLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonActionPerformed
        dispose();
        LogInPage LogInPage = new LogInPage();
        LogInPage.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLogOutButtonActionPerformed

    private void BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
          File tmpFile = new File(username+"data.ser");
        boolean Valid = tmpFile.exists();
        if (Valid ){
        float sum=0;
        try {
      File thisUserHistory = new File(username+"history.txt");
      Scanner histroryFile = new Scanner(thisUserHistory);
      while (histroryFile.hasNextLine()) {
        String data = histroryFile.nextLine();
       String[] arrOfData   =data.split("   ",3);
       sum+=Float.parseFloat(arrOfData[0]);
      }
      histroryFile.close();
    } catch (FileNotFoundException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
        BalancePage BalancePage = new BalancePage(sum);
        BalancePage.setVisible(true);}
          else{
          InputIssue InputIssue =new InputIssue();
          InputIssue.setVisible(true);
        }
    }//GEN-LAST:event_BalanceActionPerformed

    private void jSpendMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpendMoneyButtonActionPerformed
        // TODO add your handling code here:
         File tmpFile = new File(username+"data.ser");
        boolean Valid = tmpFile.exists();
        if (Valid ){
         SpendMoney SpendMoney = new SpendMoney(username);
         SpendMoney.setVisible(true);}
          else{
          InputIssue InputIssue =new InputIssue();
          InputIssue.setVisible(true);
        }
    }//GEN-LAST:event_jSpendMoneyButtonActionPerformed

    private void jHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHistoryButtonActionPerformed
        // TODO add your handling code here:
         File tmpFile = new File(username+"data.ser");
        boolean Valid = tmpFile.exists();
        if (Valid ){
        HistoryOfTransactions HistoryOfTransactions = new HistoryOfTransactions(username);
        HistoryOfTransactions.setVisible(true);}
          else{
          InputIssue InputIssue =new InputIssue();
          InputIssue.setVisible(true);
        }
    }//GEN-LAST:event_jHistoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balance;
    private javax.swing.JButton changeCurrency;
    private javax.swing.JButton jDepositButton;
    private javax.swing.JButton jHistoryButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLogOutButton;
    private javax.swing.JButton jSpendMoneyButton;
    // End of variables declaration//GEN-END:variables
}
